"""Add logout_time to activity log

Revision ID: 6d000716c4fd
Revises: 82b4ebbd98cb
Create Date: 2025-06-12 22:10:51.095555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d000716c4fd'
down_revision = '82b4ebbd98cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logout_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_column('logout_time')

    # ### end Alembic commands ###
